/*
 * generated by Xtext unknown
 */
package org.xtext.example.mydsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
