/*
 * generated by Xtext unknown
 */
package org.xtext.example.mydsl.ide

import com.google.inject.Guice
import org.xtext.example.mydsl.MyDslRuntimeModule
import org.xtext.example.mydsl.MyDslStandaloneSetup

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MyDslIdeSetup extends MyDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(new MyDslRuntimeModule, new MyDslIdeModule)
	}
}
