/*
 * generated by Xtext 2.28.0-SNAPSHOT
 */
package org.xtext.example.mydsl.formatting2;

import org.eclipse.xtext.formatting2.AbstractJavaFormatter;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.xtext.example.mydsl.myDsl.Greeting;
import org.xtext.example.mydsl.myDsl.Model;

public class MyDslFormatter extends AbstractJavaFormatter {

	protected void format(Model model, IFormattableDocument doc) {
		for (Greeting greeting : model.getGreetings()) {
			doc.format(greeting);
		}
	}
	
	protected void format(Greeting model, IFormattableDocument doc) {
		doc.prepend(model, it -> it.setNewLines(2));
		if (model.getFrom() != null) {
			doc.prepend(regionFor(model).keyword("from"), this::newLine);
			doc.interior(regionFor(model).keyword("from"), regionFor(model).keyword("!"), this::indent);
		}
	}
	
}
