/*
 * generated by Xtext 2.28.0-SNAPSHOT
 */
package org.xtext.example.mydsl.tests;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.resource.Resource.Diagnostic;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtext.example.mydsl.myDsl.Model;

@RunWith(XtextRunner.class)
@InjectWith(MyDslInjectorProvider.class)
public class MyDslParsingTest {
	@Inject
	private ParseHelper<Model> parseHelper;
	
	@Test
	public void loadModel() throws Exception {
		Model result = parseHelper.parse("Hello Xtext!");
		Assert.assertNotNull(result);
		List<Diagnostic> errors = result.eResource().getErrors();
		Assert.assertTrue("Unexpected errors: " + IterableExtensions.join(errors, ", "), errors.isEmpty());
	}
}
